### PR TITLE
Domain field added to Configuration struct and used in getAccessToken().

### PR DESCRIPTION
**Pull request by danhale-git**
This enables an Active Directory domain name to be included in the server configuration, to be used when authenticating.

I haven't been able to test this against an endpoint which doesn't required Active Directory authentication. I am presuming that passing an empty value for "directory" where an AD domain name isn't needed won't cause any problems.

### CODE REVIEW

**Comment by breed808** [comment]
Could this please be reviewed? My company uses TSS with domain authentication quite extensively. We're having to manually include this patch in our projects :disappointed:

**Comment by EndlessTrax** [comment]
Thanks for the PR @breed808. 

This patch will make `domain` a required field and will break the SDK for many users that do not use domain authentication. It cannot merge it in its current form. 

We do, however, wish to add support for this in the SDK like we have done in the [Python TSS SDK](https://github.com/thycotic/python-tss-sdk). So we will add this in the future, unless you wish you do the required changes to this PR to make it complete. If so, I would encourage you to look at the Python SDK to see how it was implemented with `Authorizers`. This is a pattern that would be used in this instance, too. If you have any questions about the implementation, both I and @amigus will be happy to answer your questions. 

Again, thank you for the PR. We appreciate the feedback.

**Comment by danhale-git** [comment]
@breed808 I ended up cloning this repository into our SCM as it doesn't seem to be actively maintained (this PR is over 9 months old). Also it has some unconventional/inconvenient patters such as [logging errors as DEBUG in a package before returning them](https://github.com/thycotic/tss-sdk-go/blob/d29883ca9fd1d6587615a5ef7ee49cb714877c3d/server/server.go#L139). I fixed the error handling and also added some helpful functions like searching for a secret name. It's a fairly small package so didn't take much work.

**Comment by EndlessTrax** [comment]
@danhale-git That's great to hear. We're currently planning the next update to this SDK, so we would be interested in seeing your changes to error handling, etc. If you wanted to push upstream, we'd be very interested in seeing those. 

cc: @amigus

**Comment by danhale-git** [comment]
@EndlessTrax I pushed a simple change that should make the Domain field backwards compatible. The field will be an empty string for those who haven't implemented it so it will be ignored.

The commit where I fixed the errors (and some golangci-lint warnings) is [here](https://github.com/danhale-git/tss-sdk-go/commit/20f554b1bc926bafacb804d3db63299c3014d434).
 
As the caller some package code, I don't want that package to print things. Instead I want it to give me information so I can decide if/when it gets printed.

Functions wrap the error, adding more context which was originally in the logged message. By the time the error gets back to the caller it reads something like:

_getting secret with id 12345: accessing resource /secret/12345: getting access token: 403 Forbidden_

This acts like a concise traceback that's also friendly for users or logging. This can get repetitive so sometimes I `return nil, err` without wrapping.

https://golang.org/doc/effective_go#errors
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
https://blog.golang.org/error-handling-and-go

Hopefully those docs agree with me because I haven't read them in some time :)

**Pull request closed without merging**
